### ISSUE TITLE
feature idea: generate morphologies

### ISSUE THREAD

**Issue by jnsbck** [jaxleyverse/jaxley#257]
I had the random idea this morning to add [MorphVAE](https://www.biorxiv.org/content/biorxiv/early/2021/06/15/2021.06.14.448271.full.pdf) or something more recent on this front to jaxley. I think this could be a cool feature which NEURON does not have, that might be really powerful. 

Things one could do:
-  build networks from sampled morphologies
- add augmentations to extracted morphologies
- sample morphologies of a specific type for some quick and dirty experiments.
- compare responses of different synthetic cells.
- ...

**Comment by michaeldeistler** [comment]
I will close this as it is quite orthogonal to Jaxley itself (and I really want to reduce the number of issues to keep an overview...)
