### ISSUE TITLE
enable synapse param sharing API

### ISSUE THREAD

**Issue by lappalainenj** [jaxleyverse/jaxley#264]
E.g.
```python
synapse_indices  = get_indices(net, edge_prop_names)
net.synapses(synapse_indices).add_to_group(group_name)
net.group_name.make_trainable("gS")
```

![IMG_7106](https://github.com/jaxleyverse/jaxley/assets/34949352/58bd612b-633d-4030-8b0c-a37c41d4048c)

**Comment by michaeldeistler** [comment]
This is made possible by #447 and #453, and a tutorial is in #464
