### ISSUE TITLE
Sign flips in synaptic current computations

### ISSUE THREAD

**Issue by kyralianaka** [jaxleyverse/jaxley#271]
In the experiment where we have two cells connected, cell 0 has HH dynamics and receives a step current input while cell 1 only has a leak channel and receives input from cell 0 (gS=0.5), we receive the following result for the ionotropic synapse (same as before when it was the "glutamate synapse"):
![image](https://github.com/jaxleyverse/jaxley/assets/48544522/895c4837-7af8-4483-8f94-fc9e5f53858b)

When we do the exact same experiment, only changing the synapse to a TanhRateSynapse and increasing the gain (gS=10), we received a sign-flipped response:  
![image](https://github.com/jaxleyverse/jaxley/assets/48544522/3cc8c953-9fb1-4601-9bc1-4c541905aa5b)

I have also repeated this experiment with a gap junction synapse I created, and it behaves just as the TanhRateSynapse does. 

It seems strange that the post-synaptic cell would hyperpolarize when a positive current is computed and depolarize when a negative current is computed, but either way, somehow the TanhRateSynapse is not consistent with the IonotropicSynapse. One potential solution is to flip the sign of the current in the TanhRateSynapse (and potentially future synapses), but like I said it seems strange to have a negative current when the presynaptic voltage is higher than rest. Maybe someone else has some more insight that I'm lacking or ideas on how to make the synapses consistent.

For these plots and some more plots see the jaxley_experiments repo.

**Comment by michaeldeistler** [comment]
Leaving this open because channels and synapses use a different sign...

**Comment by michaeldeistler** [comment]
Actually, all is good. The signs are as in NEURON (I find the neuron convention strange here, but whatever...).
