### ISSUE TITLE
.cell and .branch method autocompletion and documentation

### ISSUE THREAD

**Issue by lappalainenj** [jaxleyverse/jaxley#289]
methods like .cell and .branch do not pop up through autocompletion and documentation of them is not accessible. We can define them outside of `__getattr__` as method with `@property` decorator and document them to change that

**Comment by ntolley** [comment]
Is this still relevant? I am able to access these methods through autocompletion if I understand the issue correctly:
![image](https://github.com/user-attachments/assets/07a5fb4d-2f39-48b1-9119-31dba4a9909c)
