### ISSUE TITLE
better use of local indices

### ISSUE THREAD

**Issue by jnsbck** [jaxleyverse/jaxley#291]
(1) the function `index_of_loc` returns the highest index for the closest segment and the lowest for the furthest, see #30 and (2) it is multiplying with branch_ind because we had to rely on global compartment indices -- now this could be solved with local indices and then it is not necessary anymore to pass a branch_ind to the function
https://github.com/jaxleyverse/jaxley/blob/729c1cafdb80ab66f8c5013fbee26d7abc042613/jaxley/utils/cell_utils.py#L161

_Originally posted by @lappalainenj in https://github.com/jaxleyverse/jaxley/issues/277#issuecomment-1999963966_
            
Also see [here](https://github.com/jaxleyverse/jaxley/pull/277#issuecomment-1999672863)

**Comment by michaeldeistler** [comment]
Can this be closed @jnsbck ?

**Comment by jnsbck** [comment]
Should be adressed by #447.
