### ISSUE TITLE
Add documentation

### ISSUE THREAD

**Issue by jnsbck** [jaxleyverse/jaxley#318]
Add more documentation and comments to all user facing funtions!

I think we should agree on a common style and really spend some time to document the toolbox well. So far we are not consistent and also not everything is documented well.

I suggest something on the lines of:

```python
def foo(arg1: "type1", arg2: "type2", kwarg1: "type3" = "something") -> "type4":
    r"""Single function descriptor.
    
    Add more details in a block here. This should include formulas and 
    code examples in markdown, such that it can be rendered nicely with
    mkdocs, sphinx or whatever.
    
    ```
    x = foo(1,2,)
    ```

    Args:
        arg1 (shape): Argument 1 does ...
        arg2 (shape): Argument 2 is ...
        kwarg1 [options]: Argument 3 can ...

    Returns:
        return_var (shape): Some var that does something."""
    
    return_var = do_somthing(arg1,arg2)
    return return_var
```

EDIT: edited after comment below.

**Comment by michaeldeistler** [comment]
I will close this as I think that our documentation is ok (and of course can always be improved...)
