### ISSUE TITLE
API for setting individual synaptic parameters

### ISSUE THREAD

**Issue by kyralianaka** [jaxleyverse/jaxley#336]
Currently @Matthijspals and I index into network.edges to change individual synaptic parameters like gS and k_minus, but it would be cool to make this part of the API so that one could just specify the pre and post cell (and I guess the synapse type in case there are multiple synapse types between the pre and post cell), the parameter and to what it should be set to. 

One can currently do this for a certain parameter of *all* the synapses of that type, and maybe one can give array input also to adjust things individually (not sure, will have to test this more thoroughly), but it might be nice to expand on this.

**Comment by michaeldeistler** [comment]
This is enabled by #447
