### ISSUE TITLE
record synaptic currents

### ISSUE THREAD

**Issue by coschroeder** [jaxleyverse/jaxley#363]
at the moment it is not possible to record that

**Comment by ntolley** [comment]
Is there any interest in adding functionality for recording extracellular fields (since they're calculated directly from these currents)?

I'm planning to start playing around with jaxley to simulate LFP/EEG, happy to try and contribute if there's interest in a dedicated API

**Comment by michaeldeistler** [comment]
Yes, it would definitely be great to have this! Let me know if you need any input or would like to discuss, I would be happy to have a quick chat over zoom!

Michael

Aside: my guess is that achieving this will require to have access to x, y, z of postsynaptic compartments. Once #464 is merged, those can be accessed by doing:
```python
net._update_nodes_with_xyz()
net.copy_node_property_to_edges("x", "post")
net.edges
```

**Comment by ntolley** [comment]
I'm actually realizing that the index on this dataframe does seem to correspond to `global_comp_index`! At least the index values repeat when adding recordings for multiple current types...

**Comment by jnsbck** [comment]
Indeed, the index of whatever you are recording is written to `rec_index`, see https://github.com/jaxleyverse/jaxley/blob/32068e9e7d463f8170e1e86f02c46c18cbaaefeb/jaxley/modules/base.py#L1479-L1481. This can be the edge or comp index depending on whether the state is part of a synapse or channel.
