### ISSUE TITLE
Tests broken in main

### ISSUE THREAD

**Issue by jnsbck** [jaxleyverse/jaxley#399]
Test are broken on the main branch for me. @michaeldeistler could you check whether this is just me for some reason?

![image](https://github.com/user-attachments/assets/12999c44-f03d-40bb-8c38-d772a761124f)

**Comment by jnsbck** [comment]
If not, I will `git blame`

**Comment by michaeldeistler** [comment]
I think you have to update tridiax

**Comment by michaeldeistler** [comment]
(tests are passing on main, and github actions now run pytest)

**Comment by jnsbck** [comment]
Ah that explains it 😅

**Comment by huangziwei** [comment]
can confirm that all tests passed with the latest jaxley and tridiax.

**Comment by jnsbck** [comment]
now ran it an this was also the case for me.
