### ISSUE TITLE
Add publication

### ISSUE THREAD

**Issue by SomeUserName1** [jaxleyverse/jaxley#406]
Hi Michael,

Is there a paper or a preprint or something similar on Jaxley?

Can you shortly elaborate on the neuron model and the difference between Jaxley and NEURON?

Regarding NEURON, the book says:
>  The axon and dendrites are simple cylinders, with uniform diameters and membrane properties along their lengths. The dendrites are passive, while the soma and axon have Hodgkin-Huxley sodium, potassium, and leak currents, and are capable of generating action potentials (Hodgkin and Huxley 1952). 

However, that was written in 2004. 
From what I understand, NMODL allows for extensions, however just for ion channels.

Jaxley also implements an extensible HH-model, correct?
Is Jaxley in theory capable of supporting GPCRs in some way?
What about dendritic non-linearities, e.g. synaptic clustering, shunting, Ca-spikes and the like?

Thanks in advance
Fabian

**Comment by michaeldeistler** [comment]
The big differences between Jaxley and NEURON are that:
1) Jaxley runs on CPU and GPU without any changes to the code
2) Jaxley allows to compute the gradient with respect to parameters
