### ISSUE TITLE
The change in capacitance takes effect only at the branch(0), when len(parents) >1.

### ISSUE THREAD

**Issue by Tunenip** [jaxleyverse/jaxley#429]
The following codes will show the same result when giving a step current to branch(0):
A:
branch = jx.Branch(comp, nseg=1)
cell = jx.Cell(branch, parents=[-1,0])
cell.branch(1).set('capacitance',1)
B:
branch = jx.Branch(comp, nseg=1)
cell = jx.Cell(branch, parents=[-1,0])
cell.branch(1).set('capacitance',200)

**Comment by Tunenip** [comment]
Even though the cell.show() shows the different values.

**Comment by michaeldeistler** [comment]
Thanks for reporting this! I just released a new version of `jaxley` that fixes this issue. Please run
```pip install jaxley --upgrade```.

The following should work then:

```python
import matplotlib.pyplot as plt

import jaxley as jx
from jaxley.channels import Leak

comp = jx.Compartment()
current = jx.step_current(1, 1, 0.1, 0.025, 5.0)

branch = jx.Branch(comp, nseg=1)
cell = jx.Cell(branch, parents=[-1,0])
cell.branch(1).set("capacitance", 1)
cell.branch(0).stimulate(current)
cell.branch(1).record()
v1 = jx.integrate(cell)

branch = jx.Branch(comp, nseg=1)
cell = jx.Cell(branch, parents=[-1,0])
cell.branch(1).set("capacitance", 200)
cell.branch(0).stimulate(current)
cell.branch(1).record()
v2 = jx.integrate(cell)

fig, ax = plt.subplots(1, 1, figsize=(4, 2))
_ = ax.plot(v1.T)
_ = ax.plot(v2.T)
```

Thanks again for letting us know, and feel free to reopen the issue if anything is still unclear or behaves in an unexpected way!

All the best
Michael
