### ISSUE TITLE
replace `np.concat([np.array([0]), np.cumsum(x)])`

### ISSUE THREAD

**Issue by jnsbck** [jaxleyverse/jaxley#444]
Replace `np.concat([np.array([0]), np.cumsum(x)])` with `cumsum_leading_zero`

We can use this all over the place now.

_Originally posted by @jnsbck in https://github.com/jaxleyverse/jaxley/pull/440#discussion_r1793681794_

**Comment by michaeldeistler** [comment]
I don't think there are any places left to use this.
