### ISSUE TITLE
Speed up plotting (reduce mesh resolution)

### ISSUE THREAD

**Issue by fabioseel** [jaxleyverse/jaxley#468]
The level of detail of the meshes (create_cone_frustum_mesh, create_cylinder_mesh, create_sphere_mesh) is the main bottleneck for plotting faster (for morph plots).
However, all three of this methods start with a line defining a 'resolution'. I think it would be nice to make this a parameter and allow to produce low-resolution but fast plots.
Also useful to have the plot tests run faster ;)

**Comment by jnsbck** [comment]
hey @fabioseel would be great if you could make a PR for this if you're still working on it. Would be great to get this merged :)

**Comment by fabioseel** [comment]
I'll do that later. Should I isolate it from the other changes I made in tests?

**Comment by jnsbck** [comment]
Cool! You need to isolate it from my side. If your PR also introduces other changes, its enough if you tag the issues it's closing / list what you are tackling ;) Lemme know if you need any feedback / help :)
