### ISSUE TITLE
Clamping of Synapse: Following Synapse might also be clamped

### ISSUE THREAD

**Issue by deezer257** [jaxleyverse/jaxley#485]
If I create a network where cells are connected via RibbonSynapses, and I apply a data clamp to one of the RibbonSynapses, not only is the current synapse clamped to the defined value, but also the next synapse in sequence (with an incremented index). An example is attatched.

Jax version: 0.4.35

[Synapses_example.zip](https://github.com/user-attachments/files/17657107/Synapses_example.zip)

**Comment by jnsbck** [comment]
Hey, thanks for reporting this. Two things that would be really helpful to clarify this:
1. Did you check if this also applies to other synapses, i.e. `IonotropicSynapse`? If this is not the case I suspect this might be an issue in `jaxley_mech`.
2. If 1 is not the case, could you come up with a more minimal example, i.e. rm everything that's not strictly necessary but still produces this behavior. That would be really helpful to debug this.

**Comment by deezer257** [comment]
I tried to clamp the parameters of the IonotropicSynapse, but the library doesn't accept that in the data_clamp:

```python
import matplotlib.pyplot as plt
import jaxley as jx
import jax
from jaxley.synapses import IonotropicSynapse
from jaxley.connect import connect
from jaxley_mech.channels.hodgkin52 import Leak, Na, K
import jax.numpy as jnp
import numpy as np

# Create a new dummy network
comp_opt = jx.Compartment()
branch_opt = jx.Branch(comp_opt, nseg=1)
cell_opt = jx.Cell([branch_opt], [-1])
net_opt = jx.Network(cells=[cell_opt] * 4)

# Insert the leak channel into the cell
net_opt.insert(Leak())
net_opt.insert(Na())
net_opt.insert(K())

# Connect the cells with the synapses
connect(net_opt.cell(0),  net_opt.cell(1), IonotropicSynapse())
connect(net_opt.cell(1), net_opt.cell(2), IonotropicSynapse())
connect(net_opt.cell(2), net_opt.cell(3), IonotropicSynapse())

# Set the conductance of the synapse to zero
net_opt.cell('all').set('IonotropicSynapse_gS', 0)

inputs = jnp.ones(1000)

net_opt.delete_recordings()
net_opt.delete_stimuli()

# Record the conductance of the synapses
net_opt.cell([0,1]).record("IonotropicSynapse_gS")
net_opt.cell([1,2]).record("IonotropicSynapse_gS")
net_opt.cell([2,3]).record("IonotropicSynapse_gS")

# Clamp the cell
data_clamps = None
data_clamps = net_opt.cell([0,1]).data_clamp("IonotropicSynapse_gS", inputs, data_clamps = data_clamps)

# Integrate the network
s = jx.integrate(net_opt, 
                 data_clamps = data_clamps,
                 solver = "bwd_euler")

fig, ax = plt.subplots(2, 1, figsize=(5, 5))
ax[0].plot(s[0, :])
ax[1].plot(s[1, :])
````

This always yields the error, which doesn't make so much sense for me since I was able to set IonotropicSynapse_gS to 0 before:
![image](https://github.com/user-attachments/assets/0047791c-5170-4536-baca-c986428c0653)

I did exactly the same with the RibbonSynapse and there the data_clamp worked.

**Comment by deezer257** [comment]
I think I found the origin of the problem which it is more like an inconsistency. If I use data clamp you have to use the index of the pre synaptic cell to clamp the according Synapse, e.g. cell(pre_synaptic). However, since the synapsing indexing was changed to something like cell[pre_synaotic_cell, post_synaptic_cell] and the data_clamp function remained the old functionality, this might
caused the problem.

**Comment by jnsbck** [comment]
Thanks for checking up on this, I found the likely culprit. Will fix asap. You can keep track of the progress in #492.
