### ISSUE TITLE
Bug in connectivity_matrix_connect

### ISSUE THREAD

**Issue by kyralianaka** [jaxleyverse/jaxley#486]
The following code does not work because of issues indexing into the precell indices when creating the rows for appending multiple synapses; it only works in the pre range starts at zero.

```
comp = jx.Compartment()
branch = jx.Branch(comp, nseg=1)
cell = jx.Cell([branch], parents=[-1])
net = jx.Network([cell for _ in range(10)])

pre = net.cell(list(range(2, 5)))
post = net.cell(list(range(5, 7)))
print(len(pre.nodes), len(post.nodes))

conn_mat = np.ones((len(pre.nodes), len(post.nodes))).astype(bool)
print(conn_mat)

connectivity_matrix_connect(pre, post, IonotropicSynapse(), conn_mat)
```
One gets an index error
![image](https://github.com/user-attachments/assets/f0e7b8da-a981-4dc9-9e5c-ac25e0be0104)

NOTE: this worked about a month ago but not anymore

I don't think this was intended right @jnsbck?

**Comment by jnsbck** [comment]
This is indeed a bug. Will take care of if asap. thanks for reporting
