### ISSUE TITLE
Recording of currents not possible

### ISSUE THREAD

**Issue by deezer257** [jaxleyverse/jaxley#490]
In the newest version (pull request #491, which should be version 0.4.35) I can't record any currents of the channels since they are not included in the edges or nodes object. For other varibales which are included in the objects the recording works.

```python
from jaxley.channels.hh import HH

comp = jx.Compartment()
branch = jx.Branch(comp, nseg=1)
cell = jx.Cell([branch], [-1])
cell.insert(HH())

cell.delete_recordings()
cell.record(HH().current_name)

s = jx.integrate(cell, delta_t=0.1, t_max=1000)
```

![image](https://github.com/user-attachments/assets/c20d7785-1143-471d-a937-5925726289e3)

**Comment by jnsbck** [comment]
will be fxed in #492.
