### ISSUE TITLE
Cells read from swc files cannot be pickled

### ISSUE THREAD

**Issue by michaeldeistler** [jaxleyverse/jaxley#522]
```python
import jaxley as jx
import pickle

cell = jx.read_swc("tests/swc_files/morph_250.swc", ncomp=2)

with open("test.pkl", "wb") as handle:
    pickle.dump(cell, handle)
```

This must be because I made the `_radius_generating_fn` an attribute of cell, such that one can post-hoc run `set_ncomp()`.

**Comment by jnsbck** [comment]
oh damn. This should have been caught by `tests/test_pickle`. We should add another test_case here.

**Comment by jnsbck** [comment]
Can also make use the fixtures in `conftest.py`.
